const constants = {
    LOAD_ACCOUNTS_SUCCESS: "LOAD_ACCOUNTS_SUCCESS",
    ENROLL_STUDENT: "ENROLL_STUDENT",
    ENTER_GRADES: "ENTER_GRADES",
    LOAD_GRADES_SUCCESS: "LOAD_GRADES_SUCCESS",
    SET_REPORTCARDADDRESS: "SET_REPORTCARDADDRESS",
    CREATE_REPORTCARD_SUCCESS: "CREATE_REPORTCARD_SUCCESS",
    SEARCH_REPORTCARD_SUCCESS: "SEARCH_REPORTCARD_SUCCESS",
    SCHOOL_LOAD_SUCCESS: "SCHOOL_LOAD_SUCCESS",
    SCHOOL_ADD_SUCCESS: "SCHOOL_ADD_SUCCESS",
    LOAD_STUDENTS_SUCCESS: "LOAD_STUDENTS_SUCCESS"
}

export default constants;